[package]
name = "literate-crypto"
version = "0.0.1"
authors = ["12hbender <12hbender@proton.me>"]
edition = "2021"
description = "Literate Cryptography by 12hbender"
license = "Unlicense"

[dependencies]
docext = "0.0.8"

[dev-dependencies]
rand = "0.8"

[profile.test]
opt-level = 3
